### ISSUE TITLE
"collection of useful apps"? 

### ISSUE THREAD

**Issue by thefunkygibbon** [bob1de/hass-apps#70] opened 2021-11-18 11:18 UTC
I only see 1,  schedy.  and that hasn't been updated for a couple of years.   Whats the deal?  have you given up on making a collection?

**Comment by bob1de** [comment] 2021-11-18 13:52
Welcome and thanks for your kind inquiry.

Schedy is currently the only app in hass-apps package, you recognized this perfectly.

Back when I started working on it, the plan was to create a design which allows to add more apps in the future, but all in all I'm not so happy with the single-package approach anymore.

Other than that, this is a duplicate of #66.

**Closed by bob1de** 2021-11-18 13:52 UTC
